r = 5;
% Equations of the system
f = @(t,x) [ 2/(1+x(2)^r)-x(1);...
             2/(1+x(1)^r)-x(2) ];

% Time span for the execution of the simulations
tspan = [0,200];
                
% Plot range
xmin = 0; xmax = 5; 
ymin = 0; ymax = 5;

% Points where to start the simulations from
simulationpoints = [];
               
% Estimation of the fixed points
fixedpointestimates = [1 1;...
                       2 0.1;...
                       0.1 2];
                   
% Estimation of points of orbits
orbitsestimates = [] ;

% Execute the PPLANE alternative
% We recommend you play around with different options
figure(1); clf;
pplane_alternative( f,tspan,xmin,xmax,ymin,ymax,...
                 'fixedpoints',fixedpointestimates,...
                 'simulations',simulationpoints,...
                 'direction','both', ...
                 'reportplot', false, ...
                 'nullclines', true, ...
                 'manifolds', true, ...
                 'verbose', true, ...
                 'ntst', 40,...
                 'interactive', true)
